'use client';

import type { Config } from '@puckeditor/core';
import type { CSSProperties } from 'react';
import { cloneElement, isValidElement, useEffect, useId, useMemo, useRef, useState } from 'react';
import { briefHandoff } from '../brief-handoff';
import { resolveLink } from '../site-catalog';
import { SiteLink, useSiteLinks } from '../site-links-client';

type Item = Record<string, string>;
const themes = [{ label: 'Paper', value: 'paper' }, { label: 'Black', value: 'black' }, { label: 'Signal', value: 'signal' }];
const densities = [{ label: 'Compact', value: 'compact' }, { label: 'Standard', value: 'standard' }, { label: 'Generous', value: 'generous' }];
// Keep data and computed props as plain values in the preview. Puck's inline
// transform wraps contentEditable values in React elements, which is useful
// for prose but corrupts URLs, labels, tokens, and values used by logic.
const text = (label: string) => ({ type: 'text' as const, label });
const area = (label: string) => ({ type: 'textarea' as const, label });
const choice = (label: string, options: { label: string; value: string }[]) => ({ type: 'radio' as const, label, options });
const list = (label: string, fields: Record<string, unknown>, item: (index: number) => Item, min = 1, max = 12) => ({ type: 'array' as const, label, min, max, arrayFields: fields, defaultItemProps: item, getItemSummary: (value: Item, index?: number) => value.title || value.label || value.name || `Item ${(index || 0) + 1}` });
const url = (value?: string) => value || '#';
const editableText = (value: unknown) => {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') return String(value);
  if (!value || typeof value !== 'object') return '';
  const props = (value as { props?: { value?: unknown } }).props;
  return props && typeof props.value === 'string' ? props.value : '';
};
const themeClass = (theme?: string) => `new-component new-component--${theme || 'paper'}`;

function SignalCommandPalette({ title, placeholder, triggerLabel, commands = [], puck }: any) {
  const { pages, currentPageId } = useSiteLinks();
  const resultsId = useId();
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [active, setActive] = useState(0); const dialogRef = useRef<HTMLDialogElement>(null); const triggerRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (!event.defaultPrevented && !puck?.isEditing && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(true); } if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  useEffect(() => { const dialog = dialogRef.current; if (!dialog) return; if (open && !puck?.isEditing) { dialog.showModal(); dialog.querySelector<HTMLInputElement>('input')?.focus(); } else if (dialog.open) { dialog.close(); triggerRef.current?.focus(); } }, [open, puck?.isEditing]);
  const targets = useMemo(() => [...pages.filter(page => page.published).flatMap(page => [{ label: page.title, detail: page.path, href: { type: 'page', pageId: page.id } }, ...page.sections.map(section => ({ label: section.label, detail: page.title, href: { type: 'page', pageId: page.id, componentId: section.id } }))]), ...commands.map((item: Item) => ({ label: item.label, detail: item.detail, href: item.url }))].filter(item => `${item.label} ${item.detail}`.toLowerCase().includes(query.toLowerCase())), [commands, pages, query]);
  useEffect(() => setActive(0), [query]);
  return <section className="signal-command new-component new-component--black" aria-label={title || 'Site command palette'}><div><p className="new-kicker">Navigation system</p><h2>{title}</h2><button ref={triggerRef} type="button" onClick={() => setOpen(true)} aria-haspopup="dialog">{triggerLabel || 'Search this site'} <kbd>⌘ K</kbd></button></div><dialog ref={dialogRef} aria-label={title || 'Site command palette'} onCancel={(event) => { event.preventDefault(); setOpen(false); }}><header><label>{placeholder || 'Search pages, sections, and actions'}<input role="combobox" aria-expanded={open} aria-controls={resultsId} aria-activedescendant={targets[active] ? `${resultsId}-${active}` : undefined} aria-autocomplete="list" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); setActive(value => Math.max(0, Math.min(targets.length - 1, value + (event.key === 'ArrowDown' ? 1 : -1)))); } if (event.key === 'Enter' && targets[active]) { event.preventDefault(); const destination = resolveLink(targets[active].href, pages, currentPageId); if (destination) window.location.assign(destination); setOpen(false); } }} /></label><button type="button" onClick={() => setOpen(false)} aria-label="Close command palette">×</button></header><ul id={resultsId} role="listbox" aria-label="Search results">{targets.map((item, index) => <li id={`${resultsId}-${index}`} role="option" aria-selected={active === index} className={active === index ? 'is-active' : ''} key={`${item.label}-${index}`}><SiteLink href={item.href} onMouseEnter={() => setActive(index)} onClick={() => setOpen(false)}><strong>{item.label}</strong><span>{item.detail}</span><b aria-hidden="true">↗</b></SiteLink></li>)}</ul></dialog></section>;
}

function OrbitalProjectNavigator({ title, centreLabel, projects = [], theme }: any) {
  const [active, setActive] = useState(0); const item = projects[active] || projects[0];
  return <section className={`orbital-projects ${themeClass(theme)}`}><header><p className="new-kicker">Selected trajectories</p><h2>{title}</h2></header><div className="orbital-projects__stage"><div className="orbital-projects__centre">{centreLabel}</div><div className="orbital-projects__orbit" aria-hidden="true" />{projects.map((project: Item, index: number) => <button type="button" className={index === active ? 'is-active' : ''} aria-label={project.title || `Project ${index + 1}`} style={{ left: `${(50 + Math.cos((index / Math.max(1, projects.length)) * Math.PI * 2 - Math.PI / 2) * 40).toFixed(3)}%`, top: `${(50 + Math.sin((index / Math.max(1, projects.length)) * Math.PI * 2 - Math.PI / 2) * 40).toFixed(3)}%` }} onClick={() => setActive(index)} key={`${project.title}-${index}`} aria-pressed={index === active}>{project.short || String(index + 1).padStart(2, '0')}</button>)}</div>{item ? <article><img src={item.image} alt={item.alt || ''} /><div><p className="new-kicker">{item.category}</p><h3>{item.title}</h3><p>{item.detail}</p><a href={url(item.url)}>Open project <span aria-hidden="true">↗</span></a></div></article> : null}<ol className="sr-only">{projects.map((project: Item, index: number) => <li key={index}><a href={url(project.url)}>{project.title}</a></li>)}</ol></section>;
}

function CaseStudyIndexRail({ title, intro, entries = [], theme }: any) {
  const [active, setActive] = useState(-1);
  useEffect(() => {
    const watched = entries.flatMap((entry: Item, index: number) => {
      try {
        const target = new URL(String(entry.url || ''), window.location.href);
        if (target.origin !== location.origin || target.pathname !== location.pathname || !target.hash) return [];
        const node = document.getElementById(decodeURIComponent(target.hash.slice(1)));
        return node ? [{ node, index }] : [];
      } catch { return []; }
    });
    if (!watched.length) return;
    const update = () => { const previous = watched.filter(({ node }: { node: Element }) => node.getBoundingClientRect().top <= window.innerHeight * .4); setActive((previous.at(-1) || watched[0]).index); };
    update(); window.addEventListener('scroll', update, { passive: true }); window.addEventListener('resize', update);
    return () => { window.removeEventListener('scroll', update); window.removeEventListener('resize', update); };
  }, [entries]);
  return <section className={`case-index ${themeClass(theme)}`}><header><p className="new-kicker">Case study navigation</p><h2>{title}</h2><p>{intro}</p></header><nav aria-label={title || 'Case study chapters'}><p className="case-index__progress">{active < 0 ? 'Chapters' : `Chapter ${active + 1}`} / {entries.length}</p><ol>{entries.map((entry: Item, index: number) => <li key={`${entry.label}-${index}`}><SiteLink href={entry.url} aria-current={active === index ? 'step' : undefined} onClick={() => setActive(index)}><span>{String(index + 1).padStart(2, '0')}</span><strong>{entry.label}</strong><em>{entry.detail}</em></SiteLink></li>)}</ol></nav></section>;
}

function CapabilitySignalMap({ title, intro, nodes = [], theme }: any) { const [active, setActive] = useState(0); const current = nodes[active] || nodes[0]; return <section className={`signal-map ${themeClass(theme)}`}><header><p className="new-kicker">Capabilities map</p><h2>{title}</h2><p>{intro}</p></header><div className="signal-map__map" role="group" aria-label="Capabilities">{nodes.map((node: Item, index: number) => <button type="button" key={`${node.name}-${index}`} className={index === active ? 'is-active' : ''} onClick={() => setActive(index)} style={{ '--signal-color': node.color || '#d8ff00' } as React.CSSProperties} aria-pressed={index === active}>{node.name}</button>)}</div>{current ? <aside aria-live="polite"><strong>{current.name}</strong><p>{current.detail}</p>{current.url ? <a href={current.url}>Explore capability ↗</a> : null}</aside> : null}</section>; }

function moveTab(event: React.KeyboardEvent<HTMLDivElement>) {
  const keys = ['ArrowLeft', 'ArrowRight', 'Home', 'End'];
  if (!keys.includes(event.key)) return;
  const tabs = [...event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=tab]')];
  if (!tabs.length) return;
  event.preventDefault();
  const current = tabs.indexOf(event.target as HTMLButtonElement);
  const index = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length;
  tabs[index].click(); tabs[index].focus();
}

function LaunchSequence({ title, intro, phases = [], theme }: any) { const [active, setActive] = useState(0); const tabId = useId(); const phase = phases[active] || phases[0]; return <section className={`launch-sequence ${themeClass(theme)}`}><header><p className="new-kicker">Launch sequence</p><h2>{title}</h2><p>{intro}</p></header><div role="tablist" onKeyDown={moveTab} aria-label={`${title} phases`}>{phases.map((phase: Item, index: number) => <button type="button" role="tab" id={`${tabId}-${index}`} aria-controls={`${tabId}-panel`} tabIndex={active === index ? 0 : -1} aria-selected={active === index} key={`${phase.title}-${index}`} onClick={() => setActive(index)}>{phase.date}<strong>{phase.title}</strong></button>)}</div>{phase ? <article role="tabpanel" id={`${tabId}-panel`} aria-labelledby={`${tabId}-${active}`} tabIndex={0}><img src={phase.image} alt={phase.alt || ''} /><div><p className="new-kicker">Phase {String(active + 1).padStart(2, '0')}</p><h3>{phase.title}</h3><p>{phase.detail}</p>{phase.url ? <a href={phase.url}>Read the release ↗</a> : null}</div></article> : null}</section>; }

function ResidencyCalendar({ title, month, events = [], theme }: any) {
  const validMonth = /^\d{4}-(0[1-9]|1[0-2])$/.test(month || '');
  const start = validMonth ? new Date(`${month}-01T12:00:00Z`) : null;
  const count = start ? new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0)).getUTCDate() : 0;
  const offset = start?.getUTCDay() || 0;
  const rows = Array.from({ length: Math.ceil((count + offset) / 7) }, (_, row) => Array.from({ length: 7 }, (_, col) => row * 7 + col - offset + 1));
  return <section className={`residency-calendar ${themeClass(theme)}`}><header><p className="new-kicker">Availability calendar</p><h2>{title}</h2><span>{start ? start.toLocaleDateString('en', { month: 'long', year: 'numeric', timeZone: 'UTC' }) : 'Set a month to view the calendar'}</span></header>
    {start ? <table className="residency-calendar__grid" data-crawler-ignore><caption className="sr-only">{title} — {month}</caption><thead><tr>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day => <th scope="col" key={day}>{day}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((day, col) => {
      if (day < 1 || day > count) return <td key={col} />;
      const key = `${month}-${String(day).padStart(2, '0')}`;
      const dayEvents = events.filter((event: Item) => event.date === key);
      return <td className={dayEvents.length ? `is-${dayEvents[0].status || 'available'}` : ''} key={col}><time dateTime={key}>{day}</time>{dayEvents.map((event: Item, i: number) => <span key={i}>{event.title} ({event.status})</span>)}</td>;
    })}</tr>)}</tbody></table> : null}
    <ul className="residency-calendar__agenda">{events.map((event: Item, index: number) => <li key={`${event.date}-${index}`} className={`is-${event.status || 'available'}`}><time dateTime={/^\d{4}-\d{2}-\d{2}$/.test(event.date) ? event.date : undefined}>{event.date}</time><div><strong>{event.title}</strong><p>{event.detail}</p><small>{event.status}</small></div>{event.url ? <SiteLink href={event.url}>Details<span className="sr-only">: {event.title}</span> ↗</SiteLink> : null}</li>)}</ul></section>;
}

function TransmissionDeck({ eyebrow, title, body, status, timestamp, image, alt, actionLabel, actionUrl, theme }: any) { return <section className={`transmission-deck ${themeClass(theme)}`}><div className="transmission-deck__screen">{image ? <img src={image} alt={alt || ''} /> : null}<span className="transmission-deck__scan" aria-hidden="true" /></div><div><p className="new-kicker">{eyebrow}</p><p className="transmission-deck__status"><i aria-hidden="true" />{status}</p><h2>{title}</h2><p>{body}</p><footer><time>{timestamp}</time>{actionLabel ? <a href={url(actionUrl)}>{actionLabel} ↗</a> : null}</footer></div></section>; }

function MaterialLab({ title, materials = [], theme }: any) { const [active, setActive] = useState(0); const tabId = useId(); const material = materials[active] || materials[0]; return <section className={`material-lab ${themeClass(theme)}`}><header><p className="new-kicker">Material lab</p><h2>{title}</h2></header><div className="material-lab__swatches" role="tablist" onKeyDown={moveTab} aria-label={title || "Choose a view"}>{materials.map((item: Item, index: number) => <button type="button" role="tab" id={`${tabId}-${index}`} aria-controls={`${tabId}-panel`} tabIndex={active === index ? 0 : -1} aria-selected={active === index} onClick={() => setActive(index)} key={`${item.name}-${index}`}><i style={{ background: item.color || '#d8ff00' }} aria-hidden="true" /><span>{item.name}</span></button>)}</div>{material ? <article role="tabpanel" id={`${tabId}-panel`} aria-labelledby={`${tabId}-${active}`} tabIndex={0}><img src={material.image} alt={material.alt || ''} /><div><p className="new-kicker">{material.code}</p><h3>{material.name}</h3><p>{material.detail}</p>{material.url ? <a href={material.url}>View application ↗</a> : null}</div></article> : null}</section>; }

function PrototypeSwitcher({ title, screens = [], theme }: any) { const [active, setActive] = useState(0); const tabId = useId(); const screen = screens[active] || screens[0]; return <section className={`prototype-switcher ${themeClass(theme)}`}><header><p className="new-kicker">Prototype switcher</p><h2>{title}</h2><div role="tablist" onKeyDown={moveTab} aria-label={title || "Choose a view"}>{screens.map((item: Item, index: number) => <button type="button" role="tab" id={`${tabId}-${index}`} aria-controls={`${tabId}-panel`} tabIndex={active === index ? 0 : -1} aria-selected={active === index} onClick={() => setActive(index)} key={`${item.title}-${index}`}>{item.device}</button>)}</div></header>{screen ? <figure role="tabpanel" id={`${tabId}-panel`} aria-labelledby={`${tabId}-${active}`} tabIndex={0} className={`prototype-switcher__frame prototype-switcher__frame--${screen.device || 'desktop'}`}><img src={screen.image} alt={screen.alt || ''} /><figcaption><strong>{screen.title}</strong><span>{screen.detail}</span>{screen.url ? <a href={screen.url}>Open prototype ↗</a> : null}</figcaption></figure> : null}</section>; }

function MetricTelescope({ title, metrics = [], theme }: any) { return <section className={`metric-telescope ${themeClass(theme)}`}><header><p className="new-kicker">Outcome metrics</p><h2>{title}</h2></header><dl>{metrics.map((metric: Item, index: number) => <div key={`${metric.label}-${index}`}><dt><strong>{metric.value}</strong><span>{metric.label}</span></dt><dd><details><summary>{metric.delta || 'Read methodology'}</summary><p>{metric.detail}</p>{metric.source ? <a href={metric.source}>Source ↗</a> : null}</details></dd></div>)}</dl></section>; }

function IntegrationDirectory({ title, intro, integrations = [], theme }: any) { const [query, setQuery] = useState(''); const matches = integrations.filter((item: Item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())); return <section className={`integration-directory ${themeClass(theme)}`}><header><p className="new-kicker">Integration directory</p><h2>{title}</h2><p>{intro}</p><label>Filter integrations<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name or category" /></label></header><ul aria-live="polite">{matches.map((item: Item, index: number) => <li key={`${item.name}-${index}`}><span>{item.mark}</span><div><strong>{item.name}</strong><small>{item.category}</small><p>{item.detail}</p></div>{item.url ? <a href={item.url}>Connect <span className="sr-only">{item.name}</span> ↗</a> : null}</li>)}</ul></section>; }

function AudioFieldNotes({ title, tracks = [], theme }: any) { const [active, setActive] = useState(0); const track = tracks[active] || tracks[0]; return <section className={`audio-notes ${themeClass(theme)}`}><header><p className="new-kicker">Audio field notes</p><h2>{title}</h2></header><ol>{tracks.map((item: Item, index: number) => <li key={`${item.title}-${index}`}><button type="button" onClick={() => setActive(index)} aria-pressed={active === index}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.title}</strong><em>{item.duration}</em></button></li>)}</ol>{track ? <article><img src={track.image} alt={track.alt || ''} /><div><h3>{track.title}</h3><p>{track.detail}</p>{track.audio ? <audio controls preload="metadata" src={track.audio}>Audio is unavailable in this browser.</audio> : null}<details><summary>Transcript</summary><p>{track.transcript || 'Add a transcript for this recording.'}</p></details></div></article> : null}</section>; }

function SpecimenBoard({ title, image, alt, hotspots = [], theme }: any) { const [active, setActive] = useState(0); return <section className={`specimen-board ${themeClass(theme)}`}><header><p className="new-kicker">Annotated specimen</p><h2>{title}</h2></header><div className="specimen-board__image">{image ? <img src={image} alt={alt || ''} /> : null}{hotspots.map((item: Item, index: number) => <button type="button" key={`${item.label}-${index}`} style={{ left: item.x || '50%', top: item.y || '50%' }} onClick={() => setActive(index)} aria-pressed={active === index} aria-label={`Annotation ${index + 1}: ${item.label}`}>{index + 1}</button>)}</div><ol>{hotspots.map((item: Item, index: number) => <li className={index === active ? 'is-active' : ''} key={`${item.label}-${index}`}><button type="button" onClick={() => setActive(index)}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.label}</strong><span className="specimen-board__detail">{item.detail}</span></button></li>)}</ol></section>; }

function DecisionLog({ title, decisions = [], theme }: any) { return <section className={`decision-log ${themeClass(theme)}`}><header><p className="new-kicker">Decision log</p><h2>{title}</h2></header><ol>{decisions.map((item: Item, index: number) => <li key={`${item.title}-${index}`}><time>{item.date}</time><details open={index === 0}><summary><strong>{item.title}</strong><span>{item.status}</span></summary><p>{item.context}</p><dl><div><dt>Decision</dt><dd>{item.decision}</dd></div><div><dt>Evidence</dt><dd>{item.evidence}</dd></div></dl>{item.url ? <a href={item.url}>Read supporting work ↗</a> : null}</details></li>)}</ol></section>; }

function VersionComparator({ title, versions = [], theme }: any) { const [left, setLeft] = useState(0); const [right, setRight] = useState(Math.min(1, versions.length - 1)); const a = versions[left]; const b = versions[right]; return <section className={`version-comparator ${themeClass(theme)}`}><header><p className="new-kicker">Version comparator</p><h2>{title}</h2><div><label>Baseline<select value={left} onChange={(event) => setLeft(Number(event.target.value))}>{versions.map((item: Item, index: number) => <option value={index} key={index}>{item.title}</option>)}</select></label><label>Compare with<select value={right} onChange={(event) => setRight(Number(event.target.value))}>{versions.map((item: Item, index: number) => <option value={index} key={index}>{item.title}</option>)}</select></label></div></header><div className="version-comparator__views">{[a, b].map((item: Item, index: number) => item ? <figure key={index}><img src={item.image} alt={item.alt || ''} /><figcaption><strong>{item.title}</strong><p>{item.detail}</p></figcaption></figure> : null)}</div></section>; }

function ResearchSignalFeed({ title, entries = [], theme }: any) { const tags = [...new Set<string>(entries.map((item: Item) => item.tag).filter(Boolean))]; const [tag, setTag] = useState('All'); const filtered = tag === 'All' ? entries : entries.filter((item: Item) => item.tag === tag); return <section className={`research-feed ${themeClass(theme)}`}><header><p className="new-kicker">Research signal feed</p><h2>{title}</h2><div aria-label="Filter research" role="group"><button type="button" className={tag === 'All' ? 'is-active' : ''} onClick={() => setTag('All')}>All</button>{tags.map((value) => <button type="button" className={tag === value ? 'is-active' : ''} onClick={() => setTag(value)} key={value}>{value}</button>)}</div></header><ol>{filtered.map((item: Item, index: number) => <li key={`${item.title}-${index}`}><time>{item.date}</time><a href={url(item.url)}><img src={item.image} alt={item.alt || ''} /><div><span>{item.tag}</span><h3>{item.title}</h3><p>{item.excerpt}</p><small>{item.source} ↗</small></div></a></li>)}</ol></section>; }

function ReleaseStatusBoard({ title, updated, environments = [], note, theme }: any) { return <section className={`release-status ${themeClass(theme)}`}><header><p className="new-kicker">Release status</p><h2>{title}</h2><time>Updated {updated}</time></header><ul>{environments.map((item: Item, index: number) => <li key={`${item.name}-${index}`}><i className={`status-${item.status || 'operational'}`} aria-hidden="true" /><strong>{item.name}</strong><span>{item.version}</span><b>{item.status}</b>{item.url ? <a href={item.url}>Open <span className="sr-only">{item.name}</span> ↗</a> : null}</li>)}</ul>{note ? <aside role="status">{note}</aside> : null}</section>; }

function InteractiveBriefBuilder({ title, intro, questions = [], submitLabel, submitUrl, theme }: any) {  const safeQuestions = Array.isArray(questions) ? questions : [];  const [answers, setAnswers] = useState<Record<string, string>>({});  const [attempted, setAttempted] = useState(false);  const complete = safeQuestions.every((question: Item, index: number) => !question.required || answers[String(index)]);  const summary = safeQuestions.map((question: Item, index: number) => editableText(question.label) + ': ' + (answers[String(index)] || 'Not selected')).join('\n');  const handoff = briefHandoff(submitUrl, title, summary);  return <section className={themeClass(theme) + ' brief-builder'}><header><p className='new-kicker'>Project brief</p><h2>{title}</h2><p>{intro}</p></header><form onSubmit={(event) => { event.preventDefault(); setAttempted(true); if (complete && handoff) window.location.assign(handoff); }}>{safeQuestions.map((question: Item, index: number) => <fieldset key={editableText(question.label) + '-' + index} aria-invalid={attempted && Boolean(question.required) && !answers[String(index)]}><legend>{question.label}{question.required ? <span aria-hidden='true'> *</span> : null}</legend><div>{editableText(question.options).split('|').filter(Boolean).map((option) => <label key={option}><input type='radio' name={'question-' + index} value={option} checked={answers[String(index)] === option} onChange={() => setAnswers((current) => ({ ...current, [String(index)]: option }))} />{option}</label>)}</div></fieldset>)}<output className='brief-builder__summary'><strong>Your brief</strong><span>{summary}</span></output><button type='submit'>{submitLabel || 'Send my brief'} <span aria-hidden='true'>↗</span></button>{attempted && !complete ? <p role='alert'>Choose an option for every required question to continue.</p> : null}</form></section>; }

function ProofStack({ title, items = [], theme }: any) { const [active, setActive] = useState(0); const tabId = useId(); const item = items[active] || items[0]; return <section className={`proof-stack ${themeClass(theme)}`}><header><p className="new-kicker">Proof stack</p><h2>{title}</h2></header><div className="proof-stack__tabs" role="tablist" onKeyDown={moveTab} aria-label={title || "Choose a view"}>{items.map((proof: Item, index: number) => <button type="button" role="tab" id={`${tabId}-${index}`} aria-controls={`${tabId}-panel`} tabIndex={active === index ? 0 : -1} aria-selected={active === index} onClick={() => setActive(index)} key={`${proof.label}-${index}`}>{proof.label}</button>)}</div>{item ? <article role="tabpanel" id={`${tabId}-panel`} aria-labelledby={`${tabId}-${active}`} tabIndex={0}><img src={item.image} alt={item.alt || ''} /><div><blockquote>“{item.quote}”</blockquote><p><strong>{item.person}</strong> · {item.role}</p><dl><dt>{item.metric}</dt><dd>{item.metricLabel}</dd></dl>{item.url ? <a href={item.url}>Review evidence ↗</a> : null}</div></article> : null}</section>; }

function LocationClockboard({ title, locations = [], theme }: any) { const [now, setNow] = useState<Date | null>(null); useEffect(() => { setNow(new Date()); const timer = window.setInterval(() => setNow(new Date()), 60000); return () => window.clearInterval(timer); }, []); return <section className={`clockboard ${themeClass(theme)}`}><header><p className="new-kicker">Global studio clock</p><h2>{title}</h2></header><ul>{locations.map((location: Item, index: number) => { let local = location.time || '—'; let open = false; if (now) try { const parts = new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: location.timezone }).formatToParts(now); local = parts.map(part => part.value).join(''); const hour = Number(parts.find(part => part.type === 'hour')?.value); open = hour >= Number(location.opens || 9) && hour < Number(location.closes || 18); } catch { /* configured fallback remains visible */ } return <li key={`${location.city}-${index}`}><span>{location.label || location.city}</span><strong suppressHydrationWarning>{local}</strong><small>{location.timezone}</small><b className={open ? 'is-open' : 'is-closed'}>{now ? (open ? 'Working hours' : 'Outside working hours') : 'Local time'}</b>{location.url ? <SiteLink href={location.url}>Contact <span className="sr-only">{location.city}</span> ↗</SiteLink> : null}</li>; })}</ul></section>; }

const projectFields = { title: text('Project title'), short: text('Orbit label'), category: text('Category'), detail: area('Description'), image: text('Image URL'), alt: text('Image description'), url: text('Project link') };
const itemFields = { title: text('Title'), detail: area('Detail'), url: text('Link URL') };

export const newComponents: Config<any>['components'] = {
  SignalCommandPalette: { label: 'Signal command palette', fields: { title: text('Palette title'), placeholder: text('Search placeholder'), triggerLabel: text('Trigger label'), commands: list('Fallback commands', { label: text('Label'), detail: text('Supporting detail'), url: text('Link URL') }, (index) => ({ label: `Destination ${index + 1}`, detail: 'Page or section', url: '#' })) }, defaultProps: { title: 'Find a way through.', placeholder: 'Search pages and sections', triggerLabel: 'Open command palette', commands: [{ label: 'Selected work', detail: 'Case studies', url: '#work' }, { label: 'Start a project', detail: 'Contact', url: '#contact' }] }, render: SignalCommandPalette },
  OrbitalProjectNavigator: { label: 'Orbital project navigator', fields: { title: text('Title'), centreLabel: text('Centre label'), theme: choice('Theme', themes), projects: list('Projects', projectFields, (index) => ({ title: `Project ${index + 1}`, short: String(index + 1).padStart(2, '0'), category: 'Case study', detail: 'A project in orbit.', image: '', alt: '', url: '#' }), 3, 8) }, defaultProps: { title: 'A small universe of work.', centreLabel: 'STUDIO', theme: 'black', projects: [{ title: 'Future memory', short: '01', category: 'Identity', detail: 'A visual system for a shifting cultural object.', image: '/images/photo-1.jpg', alt: 'Abstract project image', url: '#' }, { title: 'Open weather', short: '02', category: 'Digital', detail: 'A product experience for atmospheric data.', image: '/images/photo-2.jpg', alt: 'Cloud study', url: '#' }, { title: 'Night school', short: '03', category: 'Campaign', detail: 'An after-hours learning platform.', image: '/images/photo-3.jpg', alt: 'Night portrait', url: '#' }] }, render: OrbitalProjectNavigator },
  CaseStudyIndexRail: { label: 'Case study index rail', fields: { title: text('Title'), intro: area('Introduction'), theme: choice('Theme', themes), entries: list('Chapters', { label: text('Label'), detail: text('Detail'), url: text('Section link') }, (index) => ({ label: `Chapter ${index + 1}`, detail: 'A chapter in the work', url: '#' }), 2, 10) }, defaultProps: { title: 'Inside the work.', intro: 'A navigable record of the choices that shaped it.', theme: 'paper', entries: [{ label: 'The brief', detail: 'What needed to move', url: '#brief' }, { label: 'The system', detail: 'How it took form', url: '#system' }, { label: 'The outcome', detail: 'What changed', url: '#outcome' }] }, render: CaseStudyIndexRail },
  CapabilitySignalMap: { label: 'Capability signal map', fields: { title: text('Title'), intro: area('Introduction'), theme: choice('Theme', themes), nodes: list('Capabilities', { name: text('Name'), detail: area('Description'), color: text('Signal color'), url: text('Link URL') }, (index) => ({ name: `Capability ${index + 1}`, detail: 'What this capability makes possible.', color: '#d8ff00', url: '#' }), 3, 12) }, defaultProps: { title: 'Signals, connected.', intro: 'A practice that changes shape around the problem.', theme: 'black', nodes: [{ name: 'Strategy', detail: 'Finding the useful question before making an answer.', color: '#d8ff00', url: '#' }, { name: 'Identity', detail: 'Making a system people can recognize and use.', color: '#72ddf7', url: '#' }, { name: 'Product', detail: 'Giving complex services an obvious path.', color: '#ff8c69', url: '#' }] }, render: CapabilitySignalMap },
  LaunchSequence: { label: 'Launch sequence', fields: { title: text('Title'), intro: area('Introduction'), theme: choice('Theme', themes), phases: list('Phases', { title: text('Phase title'), date: text('Date or marker'), detail: area('Detail'), image: text('Image URL'), alt: text('Image description'), url: text('Release link') }, (index) => ({ title: `Phase ${index + 1}`, date: `0${index + 1}`, detail: 'A milestone with a reason.', image: '', alt: '', url: '#' }), 2, 8) }, defaultProps: { title: 'Built in public, with intent.', intro: 'Three deliberate moves from observation to release.', theme: 'signal', phases: [{ title: 'Listen', date: '01 / Research', detail: 'Collect the friction before proposing the system.', image: '/images/photo-4.jpg', alt: 'Research notes', url: '#' }, { title: 'Prototype', date: '02 / Build', detail: 'Put the decision in visitors’ hands early.', image: '/images/photo-5.jpg', alt: 'Prototype screen', url: '#' }, { title: 'Release', date: '03 / Launch', detail: 'Ship a coherent beginning, then learn.', image: '/images/photo-6.jpg', alt: 'Launch detail', url: '#' }] }, render: LaunchSequence },
  ResidencyCalendar: { label: 'Residency calendar', fields: { title: text('Title'), month: text('Calendar month (YYYY-MM)'), theme: choice('Theme', themes), events: list('Availability', { date: text('ISO date (YYYY-MM-DD)'), title: text('Title'), detail: text('Detail'), status: text('Status'), url: text('Link URL') }, (index) => ({ date: `2026-09-${String(index + 12).padStart(2, '0')}`, title: 'Available', detail: 'Remote or in person', status: 'available', url: '#' }), 2, 16) }, defaultProps: { title: 'Available for the right collision.', month: '2026-09', theme: 'paper', events: [{ date: '2026-09-12', title: 'New York', detail: 'Studio visits and talks', status: 'limited', url: '#' }, { date: '2026-09-18', title: 'Open for collaborations', detail: 'Remote engagements', status: 'available', url: '#' }, { date: '2026-09-24', title: 'Copenhagen', detail: 'Workshop residency', status: 'booked', url: '#' }] }, render: ResidencyCalendar },
  TransmissionDeck: { label: 'Transmission deck', fields: { eyebrow: text('Eyebrow'), title: text('Title'), body: area('Body'), status: text('Status'), timestamp: text('Timestamp'), image: text('Image URL'), alt: text('Image description'), actionLabel: text('Action label'), actionUrl: text('Action URL'), theme: choice('Theme', themes) }, defaultProps: { eyebrow: 'Studio dispatch', title: 'A new language for moving images.', body: 'Current experiments, releases, and pieces of work worth keeping close.', status: 'CURRENT / STUDIO UPDATE', timestamp: 'Updated today', image: '/images/photo-7.jpg', alt: 'Studio image', actionLabel: 'Read the dispatch', actionUrl: '#', theme: 'black' }, render: TransmissionDeck },
  MaterialLab: { label: 'Material lab', fields: { title: text('Title'), theme: choice('Theme', themes), materials: list('Materials', { name: text('Name'), code: text('Specimen code'), detail: area('Detail'), color: text('Swatch color'), image: text('Image URL'), alt: text('Image description'), url: text('Link URL') }, (index) => ({ name: `Material ${index + 1}`, code: `MAT-0${index + 1}`, detail: 'A material note.', color: '#d8ff00', image: '', alt: '', url: '#' }), 2, 10) }, defaultProps: { title: 'Matter has a voice.', theme: 'paper', materials: [{ name: 'Signal green', code: 'INK-01', detail: 'A high-visibility accent for decisive moments.', color: '#d8ff00', image: '/images/photo-8.jpg', alt: 'Green printed matter', url: '#' }, { name: 'Night blue', code: 'INK-02', detail: 'A field for images and fine details to emerge from.', color: '#16264c', image: '/images/photo-9.jpg', alt: 'Blue material study', url: '#' }] }, render: MaterialLab },
  PrototypeSwitcher: { label: 'Prototype switcher', fields: { title: text('Title'), theme: choice('Theme', themes), screens: list('Screens', { title: text('Screen title'), device: choice('Device', [{ label: 'Desktop', value: 'desktop' }, { label: 'Tablet', value: 'tablet' }, { label: 'Phone', value: 'phone' }]), detail: text('Description'), image: text('Screen image URL'), alt: text('Image description'), url: text('Prototype link') }, (index) => ({ title: `Screen ${index + 1}`, device: index === 0 ? 'desktop' : 'phone', detail: 'A responsive screen.', image: '', alt: '', url: '#' }), 2, 8) }, defaultProps: { title: 'One system, many apertures.', theme: 'black', screens: [{ title: 'The whole field', device: 'desktop', detail: 'A generous desktop experience.', image: '/images/photo-1.jpg', alt: 'Desktop product interface', url: '#' }, { title: 'The essential path', device: 'phone', detail: 'A touch-first pocket interface.', image: '/images/photo-2.jpg', alt: 'Phone product interface', url: '#' }] }, render: PrototypeSwitcher },
  MetricTelescope: { label: 'Metric telescope', fields: { title: text('Title'), theme: choice('Theme', themes), metrics: list('Metrics', { value: text('Value'), label: text('Label'), delta: text('Delta or disclosure label'), detail: area('Methodology'), source: text('Source link') }, (index) => ({ value: '00%', label: `Metric ${index + 1}`, delta: 'Read method', detail: 'How this was measured.', source: '#' }), 2, 8) }, defaultProps: { title: 'Look closer at the change.', theme: 'signal', metrics: [{ value: '+42%', label: 'qualified starts', delta: 'Compared with prior launch', detail: 'Measured over eight weeks using consented first-party events.', source: '#' }, { value: '3.1×', label: 'long-form reading', delta: 'Read methodology', detail: 'Median engaged time after the case study redesign.', source: '#' }] }, render: MetricTelescope },
  IntegrationDirectory: { label: 'Integration directory', fields: { title: text('Title'), intro: area('Introduction'), theme: choice('Theme', themes), integrations: list('Integrations', { name: text('Name'), mark: text('Mark'), category: text('Category'), detail: area('Description'), url: text('Link URL') }, (index) => ({ name: `Service ${index + 1}`, mark: '◈', category: 'Workflow', detail: 'What this connection enables.', url: '#' }), 2, 16) }, defaultProps: { title: 'Designed to connect.', intro: 'A working directory of the systems around the work.', theme: 'paper', integrations: [{ name: 'Figma', mark: 'F', category: 'Design', detail: 'From working files to clearer handoffs.', url: '#' }, { name: 'GitHub', mark: '⌘', category: 'Engineering', detail: 'A legible record of the product moving forward.', url: '#' }, { name: 'Notion', mark: 'N', category: 'Operations', detail: 'Shared context for small, capable teams.', url: '#' }] }, render: IntegrationDirectory },
  AudioFieldNotes: { label: 'Audio field notes', fields: { title: text('Title'), theme: choice('Theme', themes), tracks: list('Tracks', { title: text('Track title'), duration: text('Duration'), detail: area('Description'), audio: text('Audio URL'), transcript: area('Transcript'), image: text('Cover image URL'), alt: text('Cover image description') }, (index) => ({ title: `Field note ${index + 1}`, duration: '02:16', detail: 'A recorded note.', audio: '', transcript: '', image: '', alt: '' }), 1, 10) }, defaultProps: { title: 'Notes from the field.', theme: 'black', tracks: [{ title: 'The room before opening', duration: '02:16', detail: 'Ambient notes from a space becoming public.', audio: '', transcript: 'A quiet room before visitors arrive.', image: '/images/photo-3.jpg', alt: 'Gallery interior' }, { title: 'Rain on the roof', duration: '01:42', detail: 'A texture collected during the research trip.', audio: '', transcript: 'Rain moves across the roof in changing rhythms.', image: '/images/photo-4.jpg', alt: 'Rainy roof' }] }, render: AudioFieldNotes },
  SpecimenBoard: { label: 'Specimen board', fields: { title: text('Title'), image: text('Specimen image URL'), alt: text('Image description'), theme: choice('Theme', themes), hotspots: list('Annotations', { label: text('Label'), detail: area('Description'), x: text('Horizontal position (%)'), y: text('Vertical position (%)') }, (index) => ({ label: `Annotation ${index + 1}`, detail: 'Explain this decision.', x: `${35 + index * 20}%`, y: `${35 + index * 12}%` }), 2, 8) }, defaultProps: { title: 'A system, under a lens.', image: '/images/photo-5.jpg', alt: 'Annotated printed specimen', theme: 'paper', hotspots: [{ label: 'A tighter rhythm', detail: 'Spacing creates an obvious reading order before decoration.', x: '28%', y: '38%' }, { label: 'A loud edge', detail: 'The signal color carries state and direction.', x: '70%', y: '58%' }] }, render: SpecimenBoard },
  DecisionLog: { label: 'Decision log', fields: { title: text('Title'), theme: choice('Theme', themes), decisions: list('Decisions', { title: text('Title'), date: text('Date'), status: text('Status'), context: area('Context'), decision: area('Decision'), evidence: area('Evidence'), url: text('Evidence link') }, (index) => ({ title: `Decision ${index + 1}`, date: '2026-09-01', status: 'Committed', context: 'The relevant constraint.', decision: 'The direction selected.', evidence: 'What supported it.', url: '#' }), 1, 12) }, defaultProps: { title: 'The decisions behind the surface.', theme: 'paper', decisions: [{ title: 'Let the writing lead.', date: '2026-08-14', status: 'Committed', context: 'Visitors needed orientation before visual density.', decision: 'Make the reading path visible at every viewport.', evidence: 'Prototype sessions showed faster project comprehension.', url: '#' }, { title: 'Keep the edge.', date: '2026-08-21', status: 'Observed', context: 'The identity risked becoming too polite.', decision: 'Retain a single vivid signal color.', evidence: 'The color improved recall in review sessions.', url: '#' }] }, render: DecisionLog },
  VersionComparator: { label: 'Version comparator', fields: { title: text('Title'), theme: choice('Theme', themes), versions: list('Versions', { title: text('Version title'), detail: area('What changed'), image: text('Image URL'), alt: text('Image description') }, (index) => ({ title: `Version ${index + 1}`, detail: 'What changed in this version.', image: '', alt: '' }), 2, 8) }, defaultProps: { title: 'Progress, made visible.', theme: 'black', versions: [{ title: 'v0.1 / First thought', detail: 'A dense first pass that made the ambition clear.', image: '/images/photo-6.jpg', alt: 'First design version' }, { title: 'v1.0 / Useful surface', detail: 'A more direct path to the work and its evidence.', image: '/images/photo-7.jpg', alt: 'Final design version' }] }, render: VersionComparator },
  ResearchSignalFeed: { label: 'Research signal feed', fields: { title: text('Title'), theme: choice('Theme', themes), entries: list('Research entries', { title: text('Title'), tag: text('Tag'), date: text('Date'), excerpt: area('Excerpt'), source: text('Source'), image: text('Image URL'), alt: text('Image description'), url: text('Source URL') }, (index) => ({ title: `Research note ${index + 1}`, tag: 'Reference', date: 'Sep 2026', excerpt: 'A useful observation.', source: 'Studio notebook', image: '', alt: '', url: '#' }), 2, 16) }, defaultProps: { title: 'Things that changed the next thing.', theme: 'signal', entries: [{ title: 'The beauty of legible systems', tag: 'Systems', date: 'Sep 04, 2026', excerpt: 'A reference for interfaces that disclose their own logic.', source: 'Studio notebook', image: '/images/photo-8.jpg', alt: 'Reference image', url: '#' }, { title: 'Weather as interface', tag: 'Interaction', date: 'Aug 28, 2026', excerpt: 'A sketch about using change as a way to orient people.', source: 'Field research', image: '/images/photo-9.jpg', alt: 'Clouds', url: '#' }] }, render: ResearchSignalFeed },
  ReleaseStatusBoard: { label: 'Release status board', fields: { title: text('Title'), updated: text('Updated timestamp'), note: area('Status note'), theme: choice('Theme', themes), environments: list('Environments', { name: text('Environment'), version: text('Version'), status: text('Status'), url: text('Status URL') }, (index) => ({ name: `Environment ${index + 1}`, version: 'v1.0.0', status: 'operational', url: '#' }), 1, 8) }, defaultProps: { title: 'All systems are becoming.', updated: 'just now', note: 'No incidents currently affecting the public release.', theme: 'black', environments: [{ name: 'Production', version: 'v2.4.0', status: 'operational', url: '#' }, { name: 'Preview', version: 'v2.5.0-rc.2', status: 'building', url: '#' }] }, render: ReleaseStatusBoard },
  InteractiveBriefBuilder: { label: 'Interactive brief builder', fields: { title: text('Title'), intro: area('Introduction'), submitLabel: text('Submit label'), submitUrl: text('Submit link or mailto'), theme: choice('Theme', themes), questions: list('Questions', { label: text('Question'), options: text('Options separated by |'), required: choice('Required', [{ label: 'Yes', value: 'yes' }, { label: 'No', value: '' }]) }, (index) => ({ label: `Question ${index + 1}`, options: 'Option one|Option two|Option three', required: 'yes' }), 1, 6) }, defaultProps: { title: 'Start with the shape of the thing.', intro: 'A few constraints make a better first conversation.', submitLabel: 'Send my brief', submitUrl: 'mailto:hello@example.com', theme: 'signal', questions: [{ label: 'What needs to change?', options: 'A product|An identity|A digital experience', required: 'yes' }, { label: 'When should it move?', options: 'This quarter|This year|Still defining it', required: 'yes' }] }, render: InteractiveBriefBuilder },
  ProofStack: { label: 'Proof stack', fields: { title: text('Title'), theme: choice('Theme', themes), items: list('Proof items', { label: text('Tab label'), quote: area('Quote'), person: text('Person'), role: text('Role'), metric: text('Metric'), metricLabel: text('Metric label'), image: text('Image URL'), alt: text('Image description'), url: text('Evidence URL') }, (index) => ({ label: `Proof ${index + 1}`, quote: 'A precise piece of feedback.', person: 'Client name', role: 'Role', metric: '+00%', metricLabel: 'outcome', image: '', alt: '', url: '#' }), 2, 8) }, defaultProps: { title: 'The work has receipts.', theme: 'paper', items: [{ label: 'Client voice', quote: 'The team understood the hard part before we had a name for it.', person: 'Maya Chen', role: 'Product lead', metric: '+38%', metricLabel: 'activation', image: '/images/photo-1.jpg', alt: 'Project outcome image', url: '#' }, { label: 'Independent press', quote: 'A system with unusual clarity and a real point of view.', person: 'Design Review', role: 'Editorial', metric: '12', metricLabel: 'markets', image: '/images/photo-2.jpg', alt: 'Published work', url: '#' }] }, render: ProofStack },
  LocationClockboard: { label: 'Location clockboard', fields: { title: text('Title'), theme: choice('Theme', themes), locations: list('Locations', { city: text('City'), label: text('Visible label'), timezone: text('IANA timezone'), time: text('SSR fallback time'), opens: text('Workday starts (0–23)'), closes: text('Workday ends (0–23)'), url: text('Contact URL') }, (index) => ({ city: `City ${index + 1}`, label: `Studio ${index + 1}`, timezone: 'America/New_York', time: '09:00', opens: '9', closes: '18', url: '#' }), 1, 8) }, defaultProps: { title: 'Here, there, and overlapping.', theme: 'black', locations: [{ city: 'New York', label: 'New York / Studio', timezone: 'America/New_York', time: '09:00', opens: '9', closes: '18', url: '#' }, { city: 'London', label: 'London / Partners', timezone: 'Europe/London', time: '14:00', opens: '9', closes: '18', url: '#' }, { city: 'Tokyo', label: 'Tokyo / Friends', timezone: 'Asia/Tokyo', time: '22:00', opens: '10', closes: '19', url: '#' }] }, render: LocationClockboard },
};

// A compact collection-level presentation contract keeps every new block
// editable without duplicating spacing and accent fields twenty times.
for (const component of Object.values(newComponents)) {
  const original = component.render;
  component.fields = { ...component.fields, spacing: choice('Section spacing', densities), accent: text('Accent color') };
  component.render = (props: any) => {
    const rendered = original(props);
    if (!isValidElement(rendered)) return rendered;
    const element = rendered as React.ReactElement<any>;
    const style = { ...(element.props.style || {}), '--new-space': props.spacing === 'compact' ? '52px' : props.spacing === 'generous' ? '132px' : 'clamp(52px,8vw,112px)', '--new-accent': props.accent || 'var(--site-accent,#d8ff00)' } as CSSProperties;
    return cloneElement(element, { style });
  };
}
