'use client';

import type { CSSProperties } from 'react';
import { buildCalendlyEmbedUrl } from '../../embed-utils';
import { nestedAllowlist } from '../catalog';
import { alignOptions, colorField, cropField, embedHeights, fontField, fontStyle, imageField, imagePosition, qolGapOptions, qolPaddingOptions, qolRadiusOptions, qolToneOptions, sizeOptions, themeOptions, trackingOptions, typeClass, videoField } from '../shared';
import { BeforeAfterView, CalendlyWidget, GitHubRepositoryView, HeadingPrimitive, NoticeView, ScrollFilmStrip, SocialIcon, socialPlatformOptions, videoEmbedUrl } from '../runtime';

export const portfolioComponents: Record<string, any> = {
  SplitFeature: {
        label: 'Split image + text',
        fields: { number: { type: 'text', label: 'Section number' }, title: { type: 'text', label: 'Title', contentEditable: true }, body: { type: 'textarea', label: 'Body', contentEditable: true }, titleFont: fontField('Title font'), bodyFont: fontField('Body font'), align: { type: 'radio', label: 'Text alignment', options: alignOptions }, image: imageField('Feature image'), imageCrop: cropField(), imageAlt: { type: 'text', label: 'Image description' }, imageSide: { type: 'radio', label: 'Image side', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { number: '001', title: 'A story in every frame', body: 'Use this flexible block for project introductions, services, or a short note about your process.', titleFont: 'inherit', bodyFont: 'inherit', align: 'left', image: '/images/demo-blue.jpg', imageCrop: 'center center', imageAlt: 'Abstract project artwork', imageSide: 'left', theme: 'paper' },
        render: ({ number, title, body, titleFont, bodyFont, align, image, imageCrop, imageAlt, imageSide, theme }) => <section className={`builder-split builder-split--${imageSide} builder-theme--${theme} builder-align--${align}`}><img src={image} alt={imageAlt || ''} style={imagePosition(imageCrop)} /><div className="builder-split__copy"><span className="builder-number">{number}</span><h2 style={fontStyle(titleFont)}>{title}</h2><p style={fontStyle(bodyFont)}>{body}</p></div></section>,
  },
  TextBlock: {
        label: 'Text',
        fields: { eyebrow: { type: 'text', label: 'Small intro', contentEditable: true }, heading: { type: 'text', label: 'Heading', contentEditable: true }, body: { type: 'textarea', label: 'Body', contentEditable: true }, eyebrowFont: fontField('Intro font'), headingFont: fontField('Heading font'), bodyFont: fontField('Body font'), headingSize: { type: 'select', label: 'Heading size', options: sizeOptions }, headingTracking: { type: 'select', label: 'Heading spacing', options: trackingOptions }, align: { type: 'radio', label: 'Alignment', options: alignOptions } },
        defaultProps: { eyebrow: 'A note from the studio', heading: 'Stories should feel human.', body: 'Add a short paragraph here. Click the text to edit it directly, or use the controls in the sidebar.', eyebrowFont: 'inherit', headingFont: 'inherit', bodyFont: 'inherit', headingSize: 'standard', headingTracking: 'tight', align: 'left' },
        render: ({ eyebrow, heading, body, eyebrowFont, headingFont, bodyFont, headingSize, headingTracking, align }) => <section className={`builder-text builder-text--${align}`}><p className="builder-kicker" style={fontStyle(eyebrowFont)}>{eyebrow}</p><h2 className={typeClass('builder-text-title', headingSize, headingTracking)} style={fontStyle(headingFont)}>{heading}</h2><p style={fontStyle(bodyFont)}>{body}</p></section>,
  },
  ExpandableGrid: {
        label: 'Expandable image grid',
        fields: { number: { type: 'text', label: 'Section number' }, title: { type: 'text', label: 'Title', contentEditable: true }, intro: { type: 'textarea', label: 'Introduction', contentEditable: true }, titleFont: fontField('Title font'), introFont: fontField('Introduction font'), layout: { type: 'radio', label: 'Layout', options: [{ label: 'Editorial', value: 'editorial' }, { label: 'Uniform', value: 'uniform' }, { label: 'Filmstrip', value: 'filmstrip' }] }, density: { type: 'select', label: 'Grid density', options: [{ label: 'Large images', value: 'large' }, { label: 'Medium images', value: 'medium' }, { label: 'Small images', value: 'small' }] }, gap: { type: 'radio', label: 'Gap', options: [{ label: 'Tight', value: 'tight' }, { label: 'Comfortable', value: 'medium' }, { label: 'Airy', value: 'airy' }] }, items: { type: 'array', label: 'Images', min: 1, max: 24, arrayFields: { image: imageField('Image'), crop: cropField(), alt: { type: 'text', label: 'Image description' }, caption: { type: 'text', label: 'Caption' }, shape: { type: 'select', label: 'Grid shape', options: [{ label: 'Automatic', value: 'auto' }, { label: 'Wide', value: 'wide' }, { label: 'Tall', value: 'tall' }, { label: 'Large', value: 'large' }] } }, defaultItemProps: (index) => ({ image: `/images/photo-${(index % 10) + 1}.jpg`, crop: 'center center', alt: 'Portfolio photograph', caption: `Image ${index + 1}`, shape: 'auto' }), getItemSummary: (item, index) => item.caption || `Image ${(index || 0) + 1}` } },
        defaultProps: { number: '001', title: 'Selected work', intro: 'Add, remove, and reorder as many as 24 images. The grid will reflow automatically.', titleFont: 'inherit', introFont: 'inherit', layout: 'editorial', density: 'medium', gap: 'tight', items: [{ image: '/images/photo-1.jpg', crop: 'center center', alt: 'Portfolio photograph', caption: 'Portrait study', shape: 'large' }, { image: '/images/photo-2.jpg', crop: 'center center', alt: 'Portfolio photograph', caption: 'In motion', shape: 'tall' }, { image: '/images/photo-3.jpg', crop: 'center center', alt: 'Portfolio photograph', caption: 'On location', shape: 'auto' }, { image: '/images/photo-4.jpg', crop: 'center center', alt: 'Portfolio photograph', caption: 'Golden hour', shape: 'wide' }] },
        render: ({ number, title, intro, titleFont, introFont, layout, density, gap, items }) => <section className={`builder-flex-grid builder-flex-grid--${layout} builder-flex-grid--${density} builder-flex-grid--gap-${gap}`}><div className="builder-section-title"><div><span>{number}</span><h2 style={fontStyle(titleFont)}>{title}</h2></div><p style={fontStyle(introFont)}>{intro}</p></div><div className="builder-flex-grid__grid">{(items || []).map((item: { image: string; crop?: string; alt: string; caption: string; shape: string }, index: number) => <figure className={`builder-flex-grid__item builder-flex-grid__item--${item.shape}`} key={`${item.image}-${index}`}><img src={item.image} alt={item.alt || ''} style={imagePosition(item.crop)} /><figcaption><span>{String(index + 1).padStart(2, '0')}</span>{item.caption}</figcaption></figure>)}</div></section>,
  },
  ProjectGrid: {
        label: 'Two project cards', fields: { number: { type: 'text', label: 'Section number' }, title: { type: 'text', label: 'Section title', contentEditable: true }, intro: { type: 'textarea', label: 'Introduction', contentEditable: true }, titleFont: fontField('Title font'), introFont: fontField('Introduction font'), image1: imageField('First project image'), image1Crop: cropField('First image crop'), image1Alt: { type: 'text', label: 'First image description' }, title1: { type: 'text', label: 'First project title', contentEditable: true }, url1: { type: 'text', label: 'First project link' }, image2: imageField('Second project image'), image2Crop: cropField('Second image crop'), image2Alt: { type: 'text', label: 'Second image description' }, title2: { type: 'text', label: 'Second project title', contentEditable: true }, url2: { type: 'text', label: 'Second project link' }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { number: '001', title: 'Selected projects', intro: 'A few recent stories.', titleFont: 'inherit', introFont: 'inherit', image1: '/images/reel-cinematography.jpg', image1Crop: 'center center', image1Alt: 'Project one preview', title1: 'Project one', url1: '#', image2: '/images/reel-editing.jpg', image2Crop: 'center center', image2Alt: 'Project two preview', title2: 'Project two', url2: '#', theme: 'paper' },
        render: ({ number, title, intro, titleFont, introFont, image1, image1Crop, image1Alt, title1, url1, image2, image2Crop, image2Alt, title2, url2, theme }) => <section className={`builder-projects builder-theme--${theme}`}><div className="builder-section-title"><div><span>{number}</span><h2 style={fontStyle(titleFont)}>{title}</h2></div><p style={fontStyle(introFont)}>{intro}</p></div><div className="builder-projects__grid">{[{ image: image1, crop: image1Crop, alt: image1Alt, title: title1, url: url1 }, { image: image2, crop: image2Crop, alt: image2Alt, title: title2, url: url2 }].map((project, index) => <a href={project.url} key={`${project.title}-${index}`}><div><img src={project.image} alt={project.alt || ''} style={imagePosition(project.crop)} /><span className="builder-play" aria-hidden="true">▶</span></div><strong>{project.title}</strong><span>View project ↗</span></a>)}</div></section>,
  },
  GalleryBlock: {
        label: 'Six-image gallery', fields: { number: { type: 'text', label: 'Section number' }, title: { type: 'text', label: 'Title', contentEditable: true }, intro: { type: 'textarea', label: 'Introduction', contentEditable: true }, titleFont: fontField('Title font'), introFont: fontField('Introduction font'), image1: imageField('Image 1'), image1Crop: cropField('Image 1 crop'), image1Alt: { type: 'text', label: 'Image 1 description' }, image2: imageField('Image 2'), image2Crop: cropField('Image 2 crop'), image2Alt: { type: 'text', label: 'Image 2 description' }, image3: imageField('Image 3'), image3Crop: cropField('Image 3 crop'), image3Alt: { type: 'text', label: 'Image 3 description' }, image4: imageField('Image 4'), image4Crop: cropField('Image 4 crop'), image4Alt: { type: 'text', label: 'Image 4 description' }, image5: imageField('Image 5'), image5Crop: cropField('Image 5 crop'), image5Alt: { type: 'text', label: 'Image 5 description' }, image6: imageField('Image 6'), image6Crop: cropField('Image 6 crop'), image6Alt: { type: 'text', label: 'Image 6 description' } },
        defaultProps: { number: '001', title: 'Photography', intro: 'A selection of people, places, and changing light.', titleFont: 'inherit', introFont: 'inherit', image1: '/images/photo-1.jpg', image1Crop: 'center center', image2: '/images/photo-2.jpg', image2Crop: 'center center', image3: '/images/photo-3.jpg', image3Crop: 'center center', image4: '/images/photo-4.jpg', image4Crop: 'center center', image5: '/images/photo-5.jpg', image5Crop: 'center center', image6: '/images/photo-6.jpg', image6Crop: 'center center' },
        render: ({ number, title, intro, titleFont, introFont, image1, image1Crop, image1Alt, image2, image2Crop, image2Alt, image3, image3Crop, image3Alt, image4, image4Crop, image4Alt, image5, image5Crop, image5Alt, image6, image6Crop, image6Alt }) => <section className="builder-gallery"><div className="builder-section-title"><div><span>{number}</span><h2 style={fontStyle(titleFont)}>{title}</h2></div><p style={fontStyle(introFont)}>{intro}</p></div><div className="builder-gallery__grid">{[[image1, image1Crop, image1Alt], [image2, image2Crop, image2Alt], [image3, image3Crop, image3Alt], [image4, image4Crop, image4Alt], [image5, image5Crop, image5Alt], [image6, image6Crop, image6Alt]].map(([image, crop, alt], index) => <img src={image} alt={alt || ''} style={imagePosition(crop)} key={`${image}-${index}`} />)}</div></section>,
  },
  BeforeAfter: {
        label: 'Before / after slider', fields: { label: { type: 'text', label: 'Heading', contentEditable: true }, labelFont: fontField('Heading font'), before: imageField('Before image'), beforeCrop: cropField('Before image crop'), beforeAlt: { type: 'text', label: 'Before image description' }, after: imageField('After image'), afterCrop: cropField('After image crop'), afterAlt: { type: 'text', label: 'After image description' } },
        defaultProps: { label: 'From raw frame to final grade', labelFont: 'inherit', before: '/images/photo-3.jpg', beforeCrop: 'center center', beforeAlt: 'Original image', after: '/images/photo-4.jpg', afterCrop: 'center center', afterAlt: 'Final image' },
        render: ({ label, labelFont, before, beforeCrop, beforeAlt, after, afterCrop, afterAlt }) => <div style={fontStyle(labelFont)}><BeforeAfterView label={label} before={before} beforeCrop={beforeCrop} beforeAlt={beforeAlt} after={after} afterCrop={afterCrop} afterAlt={afterAlt} /></div>,
  },
  VideoBlock: {
        label: 'Video',
        fields: {
          source: { type: 'radio', label: 'Video source', options: [{ label: 'Upload', value: 'upload' }, { label: 'YouTube / Vimeo', value: 'embed' }] },
          video: videoField('Video file'), url: { type: 'text', label: 'YouTube or Vimeo URL' }, poster: imageField('Poster image'), posterCrop: cropField('Poster crop'),
          title: { type: 'text', label: 'Accessible title' }, caption: { type: 'text', label: 'Caption', contentEditable: true }, captionFont: fontField('Caption font'),
          ratio: { type: 'radio', label: 'Aspect ratio', options: [{ label: 'Cinema', value: 'cinema' }, { label: 'Widescreen', value: 'wide' }, { label: 'Square', value: 'square' }, { label: 'Portrait', value: 'portrait' }] },
          autoplay: { type: 'radio', label: 'Uploaded video autoplay', options: [{ label: 'Off', value: 'off' }, { label: 'On (muted)', value: 'on' }] },
          loop: { type: 'radio', label: 'Uploaded video loop', options: [{ label: 'Off', value: 'off' }, { label: 'On', value: 'on' }] },
          muted: { type: 'radio', label: 'Uploaded video sound', options: [{ label: 'Sound on', value: 'off' }, { label: 'Muted', value: 'on' }] },
          controls: { type: 'radio', label: 'Uploaded video controls', options: [{ label: 'Show', value: 'show' }, { label: 'Hide', value: 'hide' }] },
        },
        defaultProps: { source: 'upload', video: '', url: '', poster: '/images/demo-blue.jpg', posterCrop: 'center center', title: 'Featured project film', caption: 'Project film', captionFont: 'inherit', ratio: 'wide', autoplay: 'off', loop: 'off', muted: 'off', controls: 'show' },
        render: ({ source, video, url, poster, posterCrop, title, caption, captionFont, ratio, autoplay, loop, muted, controls }) => {
          const isUpload = source === 'upload';
          const embed = videoEmbedUrl(url);
          const player = isUpload
            ? (video ? <video src={video} poster={poster || undefined} style={imagePosition(posterCrop)} aria-label={title || 'Portfolio video'} autoPlay={autoplay === 'on'} loop={loop === 'on'} muted={muted === 'on' || autoplay === 'on'} controls={controls !== 'hide'} playsInline preload="metadata">Your browser does not support HTML video.</video> : <div className="builder-video__empty">Upload an MP4 or WebM video</div>)
            : (embed ? <iframe src={embed} title={title || 'Embedded video'} allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen loading="lazy" /> : <div className="builder-video__empty">Paste a YouTube or Vimeo URL</div>);
          return <figure className={`builder-video builder-video--${ratio}`}>{player}{caption ? <figcaption style={fontStyle(captionFont)}>{caption}</figcaption> : null}</figure>;
        },
  },
  StickyStory: {
        label: 'Sticky project story', fields: { eyebrow: { type: 'text', label: 'Small intro', contentEditable: true }, title: { type: 'text', label: 'Title', contentEditable: true }, body: { type: 'textarea', label: 'Story', contentEditable: true }, titleFont: fontField('Title font'), bodyFont: fontField('Body font'), image: imageField('Project image'), imageCrop: cropField(), imageAlt: { type: 'text', label: 'Image description' }, imageSide: { type: 'radio', label: 'Image side', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { eyebrow: 'Project note', title: 'Hold the image while the story unfolds.', body: 'A sticky visual creates a cinematic pause on larger screens while staying naturally stacked on mobile.', titleFont: 'inherit', bodyFont: 'inherit', image: '/images/photo-7.jpg', imageCrop: 'center center', imageAlt: 'Creative project still', imageSide: 'left', theme: 'paper' },
        render: ({ eyebrow, title, body, titleFont, bodyFont, image, imageCrop, imageAlt, imageSide, theme }) => <section className={`builder-sticky builder-sticky--${imageSide} builder-theme--${theme}`}><div className="builder-sticky__image"><img src={image} alt={imageAlt || ''} style={imagePosition(imageCrop)} /></div><div className="builder-sticky__copy"><p className="builder-kicker">{eyebrow}</p><h2 style={fontStyle(titleFont)}>{title}</h2><p style={fontStyle(bodyFont)}>{body}</p></div></section>,
  },
  TimelineBlock: {
        label: 'Process timeline', fields: { eyebrow: { type: 'text', label: 'Small intro', contentEditable: true }, title: { type: 'text', label: 'Title', contentEditable: true }, titleFont: fontField('Title font'), items: { type: 'array', label: 'Steps', min: 2, max: 8, arrayFields: { marker: { type: 'text', label: 'Marker' }, title: { type: 'text', label: 'Step title' }, detail: { type: 'textarea', label: 'Detail' } }, defaultItemProps: (index) => ({ marker: String(index + 1).padStart(2, '0'), title: 'New step', detail: 'Describe what happens here.' }), getItemSummary: (item, index) => item.title || `Step ${(index || 0) + 1}` } },
        defaultProps: { eyebrow: 'How it comes together', title: 'A process with room to wander.', titleFont: 'inherit', items: [{ marker: '01', title: 'Listen', detail: 'Find the human center of the story.' }, { marker: '02', title: 'Make', detail: 'Build, shoot, sketch, and experiment.' }, { marker: '03', title: 'Refine', detail: 'Shape every detail until it feels inevitable.' }] },
        render: ({ eyebrow, title, titleFont, items }) => <section className="builder-timeline"><p className="builder-kicker">{eyebrow}</p><h2 style={fontStyle(titleFont)}>{title}</h2><ol>{(items || []).map((item: { marker: string; title: string; detail: string }, index: number) => <li key={`${item.marker}-${index}`}><span>{item.marker}</span><h3>{item.title}</h3><p>{item.detail}</p></li>)}</ol></section>,
  },
  QuoteBlock: {
        label: 'Pull quote',
        fields: { quote: { type: 'textarea', label: 'Quote', contentEditable: true }, attribution: { type: 'text', label: 'Attribution', contentEditable: true }, quoteFont: fontField('Quote font'), attributionFont: fontField('Attribution font'), size: { type: 'radio', label: 'Scale', options: [{ label: 'Quiet', value: 'quiet' }, { label: 'Feature', value: 'feature' }, { label: 'Monumental', value: 'monumental' }] }, align: { type: 'radio', label: 'Alignment', options: alignOptions }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { quote: 'The details are not the details. They make the work.', attribution: 'A creative principle', quoteFont: 'fraunces', attributionFont: 'inherit', size: 'feature', align: 'left', theme: 'paper' },
        render: ({ quote, attribution, quoteFont, attributionFont, size, align, theme }) => <blockquote className={`builder-quote builder-quote--${size} builder-quote--${align} builder-theme--${theme}`}><p style={fontStyle(quoteFont)}>“{quote}”</p><cite style={fontStyle(attributionFont)}>{attribution}</cite></blockquote>,
  },
  MarqueeBlock: {
        label: 'Kinetic marquee', fields: { text: { type: 'text', label: 'Marquee text', contentEditable: true }, font: fontField('Marquee font'), speed: { type: 'radio', label: 'Speed', options: [{ label: 'Slow', value: 'slow' }, { label: 'Medium', value: 'medium' }, { label: 'Fast', value: 'fast' }] }, direction: { type: 'radio', label: 'Direction', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { text: 'FILM · PHOTO · DESIGN · STORIES · ', font: 'inherit', speed: 'medium', direction: 'left', theme: 'lime' },
        render: ({ text, font, speed, direction, theme }) => <section className={`builder-marquee builder-marquee--${speed} builder-marquee--${direction} builder-theme--${theme}`} style={fontStyle(font)} aria-label={typeof text === 'string' ? text : 'Creative services'}><div aria-hidden="true"><span>{text}</span><span>{text}</span><span>{text}</span></div></section>,
  },
  LinkListBlock: {
        label: 'Link list',
        fields: { eyebrow: { type: 'text', label: 'Small intro', contentEditable: true }, font: fontField('Link font'), style: { type: 'radio', label: 'Style', options: [{ label: 'Index', value: 'index' }, { label: 'Buttons', value: 'buttons' }, { label: 'Minimal', value: 'minimal' }] }, links: { type: 'array', label: 'Links', min: 1, max: 12, arrayFields: { label: { type: 'text', label: 'Label' }, detail: { type: 'text', label: 'Detail' }, url: { type: 'text', label: 'URL' } }, defaultItemProps: (index) => ({ label: `Project ${index + 1}`, detail: 'Selected work', url: '#' }), getItemSummary: (item, index) => item.label || `Link ${(index || 0) + 1}` } },
        defaultProps: { eyebrow: 'Explore', font: 'inherit', style: 'index', links: [{ label: 'Cinematography', detail: 'Reel · 03:14', url: '#' }, { label: 'Photography', detail: 'Selected work', url: '#' }, { label: 'Illustration', detail: 'Sketchbook', url: '#' }] },
        render: ({ eyebrow, font, style, links }) => <nav className={`builder-link-list builder-link-list--${style}`} aria-label={typeof eyebrow === 'string' ? eyebrow : 'Selected links'}><p className="builder-kicker">{eyebrow}</p>{(links || []).map((item: { label: string; detail: string; url: string }, index: number) => <a href={item.url} key={`${item.label}-${index}`} style={fontStyle(font)}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.label}</strong><em>{item.detail}</em><b aria-hidden="true">↗</b></a>)}</nav>,
  },
  StatsBlock: {
        label: 'Facts / stats',
        fields: { font: fontField('Number font'), align: { type: 'radio', label: 'Alignment', options: alignOptions }, theme: { type: 'radio', label: 'Theme', options: themeOptions }, items: { type: 'array', label: 'Facts', min: 1, max: 6, arrayFields: { value: { type: 'text', label: 'Value' }, label: { type: 'text', label: 'Label' } }, defaultItemProps: (index) => ({ value: `${index + 1}`, label: 'Creative fact' }), getItemSummary: (item, index) => item.label || `Fact ${(index || 0) + 1}` } },
        defaultProps: { font: 'space-grotesk', align: 'left', theme: 'paper', items: [{ value: '12+', label: 'Years making' }, { value: '48', label: 'Stories shipped' }, { value: '∞', label: 'Curiosity' }] },
        render: ({ font, align, theme, items }) => <dl className={`builder-stats builder-stats--${align} builder-theme--${theme}`}>{(items || []).map((item: { value: string; label: string }, index: number) => <div key={`${item.label}-${index}`}><dt style={fontStyle(font)}>{item.value}</dt><dd>{item.label}</dd></div>)}</dl>,
  },
  CreditsBlock: {
        label: 'Project credits',
        fields: { title: { type: 'text', label: 'Heading', contentEditable: true }, font: fontField('Credits font'), columns: { type: 'radio', label: 'Columns', options: [{ label: 'One', value: 'one' }, { label: 'Two', value: 'two' }, { label: 'Three', value: 'three' }] }, items: { type: 'array', label: 'Credits', min: 1, max: 20, arrayFields: { role: { type: 'text', label: 'Role' }, name: { type: 'text', label: 'Name' } }, defaultItemProps: (index) => ({ role: `Role ${index + 1}`, name: 'Name' }), getItemSummary: (item, index) => item.role || `Credit ${(index || 0) + 1}` } },
        defaultProps: { title: 'Credits', font: 'ibm-plex-mono', columns: 'two', items: [{ role: 'Creative direction', name: 'Studio Name' }, { role: 'Photography', name: 'Collaborator Name' }, { role: 'Music', name: 'Original score' }, { role: 'Year', name: '2026' }] },
        render: ({ title, font, columns, items }) => <section className={`builder-credits builder-credits--${columns}`}><h2>{title}</h2><dl>{(items || []).map((item: { role: string; name: string }, index: number) => <div key={`${item.role}-${index}`} style={fontStyle(font)}><dt>{item.role}</dt><dd>{item.name}</dd></div>)}</dl></section>,
  },
  ContactBlock: {
        label: 'Contact footer', fields: { eyebrow: { type: 'text', label: 'Small intro', contentEditable: true }, title: { type: 'textarea', label: 'Headline', contentEditable: true }, titleFont: fontField('Headline font'), align: { type: 'radio', label: 'Alignment', options: alignOptions }, email: { type: 'text', label: 'Email address' }, buttonLabel: { type: 'text', label: 'Button label', contentEditable: true }, buttonUrl: { type: 'text', label: 'Button URL' }, theme: { type: 'radio', label: 'Theme', options: themeOptions } },
        defaultProps: { eyebrow: 'Available for select projects', title: 'Let’s make something human.', titleFont: 'inherit', align: 'left', email: 'hello@example.com', buttonLabel: 'Start a conversation', buttonUrl: 'mailto:hello@example.com', theme: 'lime' },
        render: ({ eyebrow, title, titleFont, align, email, buttonLabel, buttonUrl, theme }) => <section className={`builder-contact builder-contact--${align} builder-theme--${theme}`}><p className="builder-kicker">{eyebrow}</p><h2 style={fontStyle(titleFont)}>{title}</h2><div><a href={`mailto:${email}`}>{email}</a><a href={buttonUrl}>{buttonLabel} ↗</a></div></section>,
      },
};
